export const images = {
	appLogo: require("../assets/appLogo.png"),
	individualIcon: require("../assets/individualIcon.png"),
	doctorsIcon: require("../assets/doctorsIcon.png"),
	companyIcon: require("../assets/companyIcon.png"),
	dotIcon: require("../assets/dotIcon.png"),
	dotTwoIcon: require("../assets/dotTwoIcon.png"),
	dotThreeIcon: require("../assets/dotThreeIcon.png"),
	continueAppLogo: require("../assets/continueAppLogo.png"),
	continueBackgroundLogo: require("../assets/continueBackgroundLogo.png"),
	authBackground: require("../assets/authBackground.png"),
	fingerPrint: require("../assets/fingerPrint.png"),
	errorIcon: require("../assets/errorIcon.png"),
	ageCheckBoxTrue: require("../assets/ageCheckBoxTrue.png"),
	ageCheckBoxFalse: require("../assets/ageCheckBoxFalse.png"),
	landingBKG: require("../assets/landingBKG.png"),
	searchBKC: require("../assets/searchBKC.png"),
	doctorStanding: require("../assets/doctorStanding.png"),
	searchIcon: require("../assets/searchIcon.png"),
	cancelIcon: require("../assets/cancelIcon.png"),
	homeFalse: require("../assets/homeFalse.png"),
	records: require("../assets/records.png"),
	notifications: require("../assets/notifications.png"),
	cartIcon: require("../assets/cartIcon.png"),
	cartIconTrue: require("../assets/cartIconTrue.png"),
	accountIcon: require("../assets/accountIcon.png"),
	accountIconTrue: require("../assets/accountIconTrue.png"),
	recordsIconTrue: require("../assets/recordsIconTrue.png"),
	homeIconTrue: require("../assets/homeIconTrue.png"),
	notificationIconTrue: require("../assets/notificationIconTrue.png"),
	eclipse: require("../assets/eclipse.png"),
	star: require("../assets/star.png"),
	googleIcon: require("../assets/googleIcon.png"),
	facebookIcon: require("../assets/facebookIcon.png"),
};

export type ImageTypes = keyof typeof images
